### ISSUE TITLE
Spending [Filters: month/time/season]

### ISSUE THREAD

**Issue by haspdecrypted** [Zircoz/AmazonSummarizer#4]
**Acceptance Criteria**

- [ ] Added Month 
- [ ] Added Time
- [ ] Added Season
- [ ] Added some other feature

**Comment by RibhavKhanna** [comment]
@haspdecrypted @Zircoz please assign me this issue

**Comment by Zircoz** [comment]
Ribhav, plz continue with this I'll assign you when i'll login. Can you
also briefly describe what you are going to do ? It will prevent rework at
your end since we can pitch-in while your work is in early stages.

**Comment by RIBHAV-khanna** [comment]
Sir i am planning to make seperate columns for things mentioned and then make a pivot table and a graph. Also sir do we have to edit the given notebook or make a new one.

**Comment by Zircoz** [comment]
Okay cool, yes make a new notebook for now.

Overall as an end result we should keep the functions to be as pure as
possible and rearrange them into py files (notebooks are hard to read and
maintain). I'll happily help with that if you need me to.

Ref:
Pure functions in programming:
https://betterprogramming.pub/what-is-a-pure-function-3b4af9352f6f

PS: Don't call me sir ;-;

**Comment by RibhavKhanna** [comment]
@Zircoz please merge my pull request for both repos and make them hactoberfest accepted
